### ISSUE TITLE
Expression list not cleared after save

### ISSUE THREAD

**Issue by adeeda** [itsbth/E2Edit#6]
When I created a new file with the editor, it worked, but the list to the left was not cleared before it put in the new list.

E.g.: it went from
A
B
C

to

A
B
C
A
B
C
test

instead of

A
B
C
test

OS: Windows XP
Version: Alpha 3

**Comment by itsbth** [comment]
This issue was fixed in revision a633d52b863d4ef8674b43f92ee3dcc1de7cdd98
